// The photo gallery, in the repo rather than in a database.
//
// This file is the single source of truth for every photo the public site shows:
// which file, how big it is, what it says to a screen reader, and what the caption
// under it reads. Alt text and captions are reviewable text in a diff, and the
// image weights are decided at commit time instead of at upload time.
//
// The full-resolution originals live in the owner's Google Drive. To add a photo:
//   1. Keep the original in Drive.
//   2. Copy it into images-src/ (gitignored) named as the public slug —
//      lowercase, hyphenated, ASCII, e.g. front-porch-morning.jpg
//   3. `node scripts/optimize-images.mjs` — writes public/gallery/<slug>.jpg and
//      prints an entry with width, height and blurDataURL already filled in.
//   4. Paste the entry below, write `alt` and `caption`, and commit both the
//      derivative and this file.
//
// `src` values are stable public paths on purpose: they are emitted as absolute
// URLs in the home page's JSON-LD, so a hashed bundler URL (a static `import`)
// would churn the structured data on every rebuild.
//
// src/content/gallery.test.ts enforces the invariants — files exist, dimensions
// are true, ids are unique, alt is present, and the copy still matches
// docs/gallery-export.json.

/** Where the home page uses a photo. Each role belongs to exactly one photo. */
export type GalleryRole = "hero" | "intro";

export interface GalleryPhoto {
  /** Stable slug. Also the basename of the file in public/gallery/. */
  id: string;
  /** Public path, served straight from public/. Never a bundler import. */
  src: string;
  /** Intrinsic size of the committed file — next/image needs both to reserve space. */
  width: number;
  height: number;
  /**
   * What a screen reader announces. Required. A photo that carries no information
   * of its own gets `alt: ""` *and* `decorative: true`, so an empty string is
   * always a deliberate choice rather than an omission.
   */
  alt: string;
  /** Shown under the photo in the lightbox. Never a duplicate of `alt`. */
  caption: string;
  /** Display order, ascending. Carried over from the old database sort_order. */
  order: number;
  /** Inline LQIP, generated by scripts/optimize-images.mjs. */
  blurDataURL: string;
  /** Marks this photo as the home page's hero or intro image. */
  role?: GalleryRole;
  /** Only with `alt: ""` — states that the empty alt text is intentional. */
  decorative?: true;
}

// The annotation is what makes an entry missing `alt` (or any other required
// field) a compile error, and it keeps the optional `role` / `decorative` fields
// visible to consumers. `satisfies` is kept alongside it so the error points at
// the offending entry rather than at the whole array.
export const GALLERY: readonly GalleryPhoto[] = [
  {
    id: "farmhouse-and-barn",
    src: "/gallery/farmhouse-and-barn.jpg",
    width: 2400,
    height: 1524,
    alt: "Clover Creek Guest House farmhouse with its red barn behind it, seen from the front yard in Rush Valley, Utah",
    caption: "The farmhouse and barn",
    order: 100,
    role: "hero",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAKABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQT/xAAhEAABAwMEAwAAAAAAAAAAAAABAgMRAAQhBRIxgRNBcf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQARMf/aAAwDAQACEQMRAD8AN04OLm42Bw7ikpJwYET2aXtW1XzpW6CAiQPGkJCY9cc1Jo+LNsDAjjukBlGc/amryRl//9k=",
  },
  {
    id: "front-entrance",
    src: "/gallery/front-entrance.jpg",
    width: 2400,
    height: 1800,
    alt: "Front door and red shutters of the farmhouse, with red Adirondack chairs along the front walkway",
    caption: "Front entrance of the farmhouse",
    order: 101,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAiEAACAgIBAwUAAAAAAAAAAAABAgMRAAQhBhJBIzFRcZH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABgRAAIDAAAAAAAAAAAAAAAAAAABAhES/9oADAMBAAIRAxEAPwCptdRbRidIYWj4PqMRYq/HzgHMuy8T7O5OO2pQwWinFg3dXk9qv2B+8cJGEKgcKQLXx+ZPuTEpH//Z",
  },
  {
    id: "picnic-area-and-porch-swing",
    src: "/gallery/picnic-area-and-porch-swing.jpg",
    width: 2400,
    height: 1800,
    alt: "White picnic table and porch swing on the back lawn of the farmhouse, with the grill and old shed nearby",
    caption: "Picnic area and porch swing",
    order: 102,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIF/8QAIBAAAgEEAgMBAAAAAAAAAAAAAQIDAAQRITEyEiNBUf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAERAhL/2gAMAwEAAhEDEQA/AIuxd391NcK0rNlQighQdcDJx+1oSRK7wrJP7VODHMxJ8cdRQTPJbsTG5C4OUO1OvooILoqusjgr13x9qfuoV5jP/9k=",
  },
  {
    id: "fenced-yard-and-farmland-view",
    src: "/gallery/fenced-yard-and-farmland-view.jpg",
    width: 2400,
    height: 1800,
    alt: "Grassy side yard with a wood-rail fence and shade tree, looking out over open Rush Valley farmland",
    caption: "Fenced yard and farmland view",
    order: 103,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAiEAACAQMDBQEAAAAAAAAAAAABAwIABBEFIjESIVFxkdH/xAAVAQEBAAAAAAAAAAAAAAAAAAABA//EABcRAAMBAAAAAAAAAAAAAAAAAAABAhH/2gAMAwEAAhEDEQA/AKR16yfmDEslAjxzR7K/tk6lcOWt2GLgBLABGOrmhMsoROAxn0flGkkbt0u3qpu6HEf/2Q==",
  },
  {
    id: "front-room",
    src: "/gallery/front-room.jpg",
    width: 2400,
    height: 1800,
    alt: "Front room of the farmhouse with an electric fireplace, maroon leather sofa, and staircase to the loft",
    caption: "Front room",
    order: 104,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAED/8QAIxAAAgICAAUFAAAAAAAAAAAAAQIDEQAEBRIhIjEjQVGh0f/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwCTcWjhChnLgoGKVZ815zFNjWnKz+oYzzWKpgaNfeF1tdJuHyyMW5ooA60ff8wWz3asIJ6UxA+OuGhsgcv/2Q==",
  },
  {
    id: "front-room-seating",
    src: "/gallery/front-room-seating.jpg",
    width: 2400,
    height: 1800,
    alt: "Front room seating area with two maroon leather couches, a round area rug, and coffee table",
    caption: "Front room seating",
    order: 105,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAP/xAAjEAACAQQCAAcAAAAAAAAAAAABAgMABBESBQYTIUFRYYGx/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABcRAQEBAQAAAAAAAAAAAAAAABEAATH/2gAMAwEAAhEDEQA/ADxcnbyXiMsD67ZKlxjzPrVuQ5G2N+4itZYowdQuABn8+6N15EuuK8GZFZQ5PyaL2eeSKO3ijbRYsquvtR4JJvG//9k=",
  },
  {
    id: "dining-nook",
    src: "/gallery/dining-nook.jpg",
    width: 2400,
    height: 1800,
    alt: "Drop-leaf dining table for two near the front entrance, with red curtains and farmhouse trim",
    caption: "Dining nook",
    order: 106,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAhEAACAQQCAgMAAAAAAAAAAAABAwIABBESBSETQSIxMv/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAYEQACAwAAAAAAAAAAAAAAAAAAAQIREv/aAAwDAQACEQMRAD8ATkHrS9EhHyxY2Ymc/jAqZSrbkLcQXygt2bnXaJ+RPrr6xipSsSe4SJkN5dE590alwtLiDlRGQehLsCiyhFKj/9k=",
  },
  {
    id: "kitchen",
    src: "/gallery/kitchen.jpg",
    width: 2400,
    height: 1800,
    alt: "Farmhouse kitchen with a full-size refrigerator, wood cabinets, and a dining table with area rug",
    caption: "Kitchen",
    order: 107,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACMQAAICAgECBwAAAAAAAAAAAAECAwQREgAhcQUUIkFhgZH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQARIf/aAAwDAQACEQMRAD8AXdfKNImd1kQuuo6DJz+jrwljxeuXAirxIjDUhhn7HzzPXrk8V6dY5Co29u3KcNyV6sbNqSVBPpGM9uEisumdv//Z",
  },
  {
    id: "master-bedroom",
    src: "/gallery/master-bedroom.jpg",
    width: 2400,
    height: 1800,
    alt: "King-size master bedroom bed with a red plaid patchwork quilt, wood headboard, and a small shelf nightstand",
    caption: "Master bedroom",
    order: 108,
    role: "intro",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMEBv/EACEQAAIBAwQDAQAAAAAAAAAAAAECAwARIQQFEhMiMVFh/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABcRAAMBAAAAAAAAAAAAAAAAAAABITH/2gAMAwEAAhEDEQA/AEyoI9T19t3GLfasnl0jtMypxGOPZIQBYZ9YrLbvI53eTyPwfmKEF54GErMwI9XokoJNP//Z",
  },
  {
    id: "master-bedroom-wardrobe",
    src: "/gallery/master-bedroom-wardrobe.jpg",
    width: 2400,
    height: 1800,
    alt: "Master bedroom wardrobe area with a wood dresser, standing mirror, and the foot of the quilted bed",
    caption: "Master bedroom wardrobe",
    order: 109,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQF/8QAIhAAAgEDBAIDAAAAAAAAAAAAAQIDAAQREiExQQUTUXGx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAZEQACAwEAAAAAAAAAAAAAAAAAEQESISL/2gAMAwEAAhEDEQA/AHn0S+LJjbDRzldu871mWFxavfyRzLK6qvAbG/zQQzyAPDqPqLl9HWePyp5lC6ygC4PQ5+6ncPB68s//2Q==",
  },
  {
    id: "bathroom-tub-and-shower",
    src: "/gallery/bathroom-tub-and-shower.jpg",
    width: 2400,
    height: 1800,
    alt: "Bathroom with a tub-and-shower combo and vanity, with a washer and dryer along the same wall",
    caption: "Bathroom with tub and shower",
    order: 110,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgQF/8QAIBAAAQMEAwEBAAAAAAAAAAAAAQIDBAARISIFMUESof/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/AKecEhmNPdSlxshN0rGPQcftZXCPzn4Lymwl1AfH2pw3UNfM0klLJbF7Hcd5oxzgBljVI1PQtRrhIGt//9k=",
  },
  {
    id: "bathroom-washer-and-dryer",
    src: "/gallery/bathroom-washer-and-dryer.jpg",
    width: 2400,
    height: 1800,
    alt: "Bathroom with a toilet and a side-by-side washer and dryer, with wood-look flooring",
    caption: "Bathroom with washer and dryer",
    order: 111,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQT/xAAgEAACAQQDAAMAAAAAAAAAAAABAgMABBETBRIxIUFh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABAhH/2gAMAwEAAhEDEQA/AKbC/PS2c3TsswfpGzD6/KQ0R3OuSXL4GQo+MGguOSNOPtpdaFwhIJHmfaatJG0DyhONio//2Q==",
  },
  {
    id: "loft",
    src: "/gallery/loft.jpg",
    width: 2400,
    height: 1800,
    alt: "Two full-size beds with patchwork quilts in the upstairs loft, tucked under the sloped farmhouse ceiling",
    caption: "The Loft",
    order: 112,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEC/8QAIRAAAgIBBAIDAAAAAAAAAAAAAQIDEQQAEhMhFEEiMbH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGBEAAgMAAAAAAAAAAAAAAAAAADEBESH/2gAMAwEAAhEDEQA/AJHKpjM08sTrD8zGpsEDuq960+4x+Rj8SCWn4i20Cx9AetLg4yowbe7dVTEaHPwULs/LLZN1u6/NFiEqWf/Z",
  },
  {
    id: "loft-sitting-area",
    src: "/gallery/loft-sitting-area.jpg",
    width: 2400,
    height: 1800,
    alt: "Loft sitting area with an armchair, dresser, and foosball table, next to the foot of the loft beds",
    caption: "Loft sitting area",
    order: 113,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAIBAAAgICAgIDAAAAAAAAAAAAAQMCBAARBRJBkRNhof/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAWEQEBAQAAAAAAAAAAAAAAAAABABL/2gAMAwEAAhEDEQA/ACWwtDUHQYBIAiJ+8l57kF0rMLCEiMWbj8IPUDXn9zbsJTBvVaVwA8QiBv1ivw/HSp7ZUU0k72wdiPeFoCTN/9k=",
  },
  {
    id: "welcome-sign",
    src: "/gallery/welcome-sign.jpg",
    width: 2165,
    height: 1798,
    alt: "Wooden welcome sign for Clover Creek Guest House at 1475, with the phone number for availability in Rush Valley, Utah",
    caption: "Welcome sign",
    order: 114,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAQP/xAAgEAACAQMEAwAAAAAAAAAAAAABAgMAERIEITEyFEHB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAZEQACAwEAAAAAAAAAAAAAAAAAAQIREiH/2gAMAwEAAhEDEQA/ALmKAO58eFny62ttQI4XLKYYwxJBCryLc06mcM7jDobA3qEeqK52Tbf39qdy5Q2Gf//Z",
  },
] satisfies readonly GalleryPhoto[];

/** The one photo that fills a named slot on the home page. */
export function photoForRole(role: GalleryRole): GalleryPhoto {
  const match = GALLERY.filter((p) => p.role === role);
  if (match.length !== 1) {
    // A build-time mistake, not a runtime condition — fail loudly rather than
    // silently rendering the wrong photo (or none) on the most important page.
    throw new Error(`Expected exactly one gallery photo with role "${role}", found ${match.length}`);
  }
  return match[0];
}
